# Generated by Django 4.2 on 2023-10-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="exhange_rate",
            field=models.FloatField(blank=True, null=True, verbose_name="currency exchange rate"),
        ),
    ]
